### ISSUE TITLE
Version 0.2.1 is not found when running gradle sync - 0.2.0 works, but not the latest release.

### ISSUE THREAD

**Issue by algoflows** [xxfast/Decompose-Router#13]
Version 0.2.1 is not found when running gradle sync - 0.2.0 works, but not the latest release.

**Comment by xxfast** [comment]
Hi. Can you share the error you are seeing on the sync window?

**Comment by xxfast** [comment]
Hi again!. Issue is fixed. I've also updated my sample with 0.2.1, PR available [here](https://github.com/xxfast/NYTimes-KMP/pull/28)
