### ISSUE TITLE
Object is not abstract and does not implement abstract base class member public abstract fun describeContents(): Int 

### ISSUE THREAD

**Issue by Deaths-Door** [xxfast/Decompose-Router#14]
```kotlin
import com.arkivanov.essenty.parcelable.Parcelable
import com.arkivanov.essenty.parcelable.Parcelize

sealed class RootGraph : Parcelable {
    @Parcelize object UserLibrary : RootGraph()
    @Parcelize object ExploreNewContent : RootGraph()
    @Parcelize object EventMaps : RootGraph()
    @Parcelize object LocalMusic : RootGraph()
   // @Composable
  //  abstract fun content(globalViewModel : GlobalViewModel)
}

```
I get error
 - This class does not have a constructor
 - Object  is not abstract and does not implement abstract base class member public abstract fun describeContents(): Int defined in com.deathsdoor.chillback.common.ui.navigation.RootGraph but then i can't manually override the function if i want to 
 
Also the doc is lacking , i mean so push function for router

**Comment by xxfast** [comment]
Hi. Thanks for the issue. Have you included the parcelize plugin on your module? 

This is required for android, just like any other android module

**Comment by Deaths-Door** [comment]
Yes i tried with parcelize plugin , and different versions of the 'optional' (other) libraries as well but i get that issue. If i but @Parcelize on the class itself i get , Object is not abstract and does not implement abstract base class member public abstract fun describeContents(): Int defined in some decompose package. As well as , I am unable to 'find' the methods given in the doc

**Comment by xxfast** [comment]
I see what the issue is. 

You should only need to annotate with `@Parcelize` once on the top-level sealed class. Here's the [sample implementation](https://github.com/xxfast/NYTimes-KMP/blob/main/app/src/commonMain/kotlin/io/github/xxfast/nytimes/screens/home/HomeStateModels.kt)
```kotlin
@Parcelize
sealed class StoryHomeScreen: Parcelable {
  object List: StoryHomeScreen()
  data class Details(val section: TopStorySection, val uri: ArticleUri, val title: String): StoryHomeScreen()
}
```

The documentation is wrong and I will use this issue to correct this. Thanks for pointing this out 👍 Hopefully the above fix works for you

**Comment by xxfast** [comment]
Yup will do

**Comment by arkivanov** [comment]
I have just checked and the original code works for me just fine. Not sure what was the actual issue.

**Comment by xxfast** [comment]
yeah, you are right @arkivanov, I'm assuming the issue was an outdated cache prior to adding `kotlin-parcelize` 

Nevertheless, I've update the readme to go with the simpler approach of declaring `@Parcelize` once on the sealed type
