### ISSUE TITLE
iOS swipe gesture to exit page is not implemented?

### ISSUE THREAD

**Issue by wtfisthatzzz** [xxfast/Decompose-Router#20]
iOS swipe gesture to exit page is not implemented?

**Comment by xxfast** [comment]
Yup not yet implemented, should be doable with Decompose. Will add this to the roadmap

**Comment by arkivanov** [comment]
The predictive back gesture is now supported by Decompose. Most likely no changes are required here. Just bump Decompose version to `2.1.0-compose-experimental-alpha-01` and try following this guide: https://arkivanov.github.io/Decompose/extensions/compose/#predictive-back-gesture

**Comment by xxfast** [comment]
Thanks @arkivanov! Will migrate to `2.1.0-compose-experimental-alpha-01` in the next snapshot

**Comment by arkivanov** [comment]
Decompose [2.1.0-experimental-compose-alpha-02](https://github.com/arkivanov/Decompose/releases/tag/2.1.0-experimental-compose-alpha-02) is released, consider using this version instead. Please note that you can now update your Android SDK and set `compileSdkVersion` and `targetSdkVersion` to `34`, instead of `compileSdkPreview = "UpsideDownCake"`.

**Comment by xxfast** [comment]
Thanks 👍 Had to double check the version name, but [maven](https://repo.maven.apache.org/maven2/com/arkivanov/decompose/decompose/2.1.0-compose-experimental-alpha-02/) says it is still `2.1.0-compose-experimental-alpha-02`.

**Comment by arkivanov** [comment]
Ah, I keep making this mistake! That's just the release label is incorrect, Maven is the source of truth. Thanks for noticing!

**Comment by xxfast** [comment]
Hi @arkivanov I've updated to the latest version but swipe to go back on ios doesn't seem to work off the shelve. Does this need special setup for iOS?

**Comment by arkivanov** [comment]
Yes, there is one additional step, please see the docs: https://arkivanov.github.io/Decompose/extensions/compose/#predictive-back-gesture-on-other-platforms

Also I recommend updating to `alpha-05` as it contains a bug fix related to predictive back gesture.

**Comment by xxfast** [comment]
ah right totally missed that step - will do

**Comment by xxfast** [comment]
It works 🙌 Use the latest decompose-router snapshot along with `2.1.0-compose-experimental-alpha-03`. You can follow the official decompose [guide](https://arkivanov.github.io/Decompose/extensions/compose/#predictive-back-gesture-on-other-platforms) linked above inorder to incorporate in your ios app - or check out this [diff](https://github.com/xxfast/NYTimes-KMP/commit/3e079846714e71ffd0399963804e5460d2f9c331) from the sample

https://github.com/xxfast/Decompose-Router/assets/13775137/674f117f-aaba-4784-902e-c933c1361a90

@arkivanov Looks like `alpha-05` seems to break predictive back on Android, will raise an issue on decompose for this
