### ISSUE TITLE
Sample on documentation uses deprecated code

### ISSUE THREAD

**Issue by nicolasf** [xxfast/Decompose-Router#77]
The `@Parcelize` used on the documentation is deprecated, suggesting using a kotlinx-serialization implementation.

**Comment by xxfast** [comment]
Hi @nicolasf I'm currently planning to migrate to Decompose [2.2.0-compose-experimental-alpha03](https://github.com/arkivanov/Decompose/releases/tag/2.2.0-compose-experimental-alpha03) 

This is a breaking API change so it will be in the next release (`0.6.0`)

**Comment by xxfast** [comment]
Hi. I've updated the docs [here](https://xxfast.github.io/Decompose-Router/using-decompose-router.html). Will be releasing 0.6.0 (that supports latest stable decompose) soon.

**Comment by umesh0492** [comment]
please update the docs.

**Comment by xxfast** [comment]
Done 👍 docs on [Model driven navigation here](https://xxfast.github.io/Decompose-Router/using-decompose-router.html#model-driven-navigation)
