### ISSUE TITLE
Compose for Web (Wasm) support

### ISSUE THREAD

**Issue by nowiwr01w** [xxfast/Decompose-Router#82]
Hello, can you please share your thoughts about Kotlin/Wasm support?
Now Kotlin/Wasm officially supported by JetBrains and available at [Wizard](https://kmp.jetbrains.com) to build Kotlin Multiplatform project
![image](https://github.com/xxfast/Decompose-Router/assets/39140585/23c40e5f-4397-4089-a9f1-7c58457576b5)

**Comment by xxfast** [comment]
Hi!

Will wait for [Decompose-3.0.0](https://github.com/arkivanov/Decompose/releases/tag/3.0.0-alpha03) stable release which adds wasm target. Will keep this issue open till then

**Comment by Skeptick** [comment]
Hi! Decompose 3.0 is finally out. Can we wait for a new version of the library?

**Comment by xxfast** [comment]
Available now on [0.8.0](https://github.com/xxfast/Decompose-Router/releases/tag/0.8.0)
