### ISSUE TITLE
ViewModel onDestroy

### ISSUE THREAD

**Issue by hulkdx** [xxfast/Decompose-Router#99]
ViewModel onDestroy won't get called on navigation back

**Comment by xxfast** [comment]
Hi @hulkdx Sorry for the super late reply

By `ViewModel`, do you mean the  [common view-models](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-viewmodel.html) from `org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose:`?

**Comment by xxfast** [comment]
Currently there's no plans to provide support for [common view-models](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-viewmodel.html). However, decompose-router API is architecture agnostic and it is quite flexible to do this yourself with something like 
```kotlin
val viewModel: YourViewModel = rememberOnRoute(type = YourViewModel::class, key = id) {
  YourViewModel(id = id)
}
    
DisposableEffect(viewModel) {
  onDispose { viewModel.onDestroy() }
}
```

Feel free to comment if you have more feedback. Happy to provide a first-party integration if there's enough demand :)
